[package]
name = "palsavetool_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.28"
uesave = { git = "https://github.com/trumank/uesave-rs.git", version = "0.3.0" }
